new branch1

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -7,6 +7,30 @@ on:
     branches: [ "main" ]
 
 jobs:
+  unit-tests:
+
+    runs-on: ubuntu-latest
+
+    strategy:
+      matrix:
+        node-version: [18.x, 20.x, 22.x]
+
+    steps:
+    - uses: actions/checkout@v4
+    - name: Use Node.js ${{ matrix.node-version }}
+      uses: actions/setup-node@v4
+      with:
+        node-version: ${{ matrix.node-version }}
+        cache: 'npm'
+
+    - name: "Installing dependencies"
+      run: npm ci
+
+    - name: "Running Test cases"
+      env:
+        MONGO_TEST_URL: ${{ secrets.MONGO_TEST_URL }}
+      run: npm test -- --detectOpenHandles --verbose || (echo "Tests failed! Check logs." && exit 1)
+
   build:
 
     runs-on: ubuntu-latest
@@ -22,6 +46,9 @@ jobs:
       with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
-    - run: npm ci
-    - run: npm run build --if-present
-    - run: npm test
+
+    - name: "Installing dependencies"
+      run: npm ci
+     
+    - name: "Build Command"
+      run: npm run build --if-present
